import _ from 'lodash';
import React, { useEffect } from 'react';
import TestIntroduction from './TestIntroduction';
import TestContainer from './TestContainer';
import QuestionCard from './QuestionCard';
import QuestionOption from '../testWizardUtilities/QuestionOption';
import QuestionOptions from '../testWizardUtilities/QuestionOptions';
import {
    useActions,
    useStore,
    useStoreAttribute,
} from '../../hooks';

export default function() {
    const vocabulary = useStore('vocabularyTest');
    const vocabularyActions = useActions('vocabularyTest');
    const timerActions = useActions('timer');
    const timerActive = useStoreAttribute('timer', 'timerActive');

    const getQuestions = () => _.get(vocabulary, 'questions', []);

    const getAnswers = () => _.get(vocabulary, 'answers', []);

    const getProgressIndex = () => _.get(vocabulary, 'progressIndex', 0);

    const getAnswer = progressIndex => getAnswers()[progressIndex] || {};

    const getCurrentAnswer = () => getAnswers()[getProgressIndex()] || {};

    const getCurrentAnswerText = () => _.get(getCurrentAnswer(), 'text', '');

    const getCurrentQuestion = () => getQuestions()[getProgressIndex()] || {};

    const getTotalQuestionsCount = () => _.size(getQuestions());

    const getProgress = () => _.get(vocabulary, 'progress', 'not-started');

    const getCurrentQuestionTimeLimit = () => _.get(getCurrentQuestion(), 'timeLimit', 20);

    const setAnswerMetadata = (metadata, progressIndex = getProgressIndex()) => {
        const answers = [...getAnswers()];
        answers[progressIndex] = {
            ...getAnswer(progressIndex),
            ...metadata,
        };
        vocabularyActions.setAnswers(answers);
    };

    const answer = (progressIndex = getProgressIndex()) => {
        const answers = [...getAnswers()];
        const originalAnswer = getAnswer(progressIndex);
        answers[progressIndex] = {
            ...originalAnswer,
            endTime: new Date().toISOString(),
            attempted: 'text' in originalAnswer,
        };
        if (progressIndex < getTotalQuestionsCount() - 1) {
            answers[progressIndex + 1] = {
                ...getAnswer(progressIndex + 1),
                startTime: new Date().toISOString(),
                seen: true,
            };
            vocabularyActions.nextQuestion(answers);
        } else {
            vocabularyActions.setAnswers(answers);
        }
    };

    const skipAnswer = (progressIndex = getProgressIndex()) => {
        if (progressIndex < getTotalQuestionsCount() - 1) {
            const answers = [...getAnswers()];
            answers[progressIndex + 1] = {
                ...getAnswer(progressIndex + 1),
                startTime: new Date().toISOString(),
                seen: true,
            };
            vocabularyActions.nextQuestion(answers);
        }
    };

    const onStartClick = () => {
        vocabularyActions.startTest();
        // Set the start time on the current answer when the test starts.
        setAnswerMetadata({
            startTime: new Date().toISOString(),
            seen: true,
        });
    };

    const onNextClick = userPrompt => {
        // TODO There should be a better way of doing this.
        // We are basically skipping the time difference check by clearing the timestamp, might seem like a hack in the design.
        timerActions.clearTimestamp();
        const progressIndex = getProgressIndex();
        if (progressIndex >= getTotalQuestionsCount() - 1) {
            timerActions.endTimer();
            vocabularyActions.endTest();
        }
        // The userPrompt will be true if the onNextClick press is generated by user themselves.
        if (userPrompt) {
            answer();
        } else {
            skipAnswer();
        }
    };

    const onPreviousClick = () => vocabularyActions.previousQuestion();

    const onAnswerChange = e => setAnswerMetadata({ text: _.get(e, 'target.value') });

    useEffect(() => {
        if (!timerActive && _.eq(getProgress(), 'in-progress')) {
            onNextClick();
        }
    // TODO React Gurus might be mad.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [timerActive]);

    useEffect(() => {
        // Progress index changed meaning it's either a new question or we are initializing a question.
        timerActions.startTimer(getCurrentQuestionTimeLimit());
    // TODO - We are potentially making React Guru's angry by disabling this lint. Must revisit in the future.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [vocabulary.progressIndex]);

    const getViewMap = () => {
        const total = getTotalQuestionsCount();
        const current = total ? getProgressIndex() + 1 : 0;
        const currentQuestion = getCurrentQuestion();
        const currentAnswerText = getCurrentAnswerText();
        return {
            'not-started': <TestIntroduction
                onStartClick={onStartClick}
                total={total}
            />,
            'in-progress': (
                <TestContainer
                    current={current}
                    onNextClick={() => onNextClick(true)}
                    onPreviousClick={onPreviousClick}
                    total={total}
                >
                    {
                        current
                            ? (
                                <QuestionCard
                                    difficulty={currentQuestion.difficulty}
                                    word={currentQuestion.word}
                                >
                                    <QuestionOptions
                                        answer={currentAnswerText}
                                        onAnswerChange={onAnswerChange}
                                    >

                                        {_.map(currentQuestion.options, (option, index) => (
                                            <QuestionOption
                                                key={index}
                                                text={option.text}
                                            />
                                        ))}
                                    </QuestionOptions>
                                </QuestionCard>
                            )
                            : null
                    }
                </TestContainer>
            ),
        };
    };

    const progress = getProgress();
    const viewMap = getViewMap();
    return viewMap[progress];
}
