import axios from 'axios';
import MockAdapter from 'axios-mock-adapter';
import service from '../../services/TestSessionService';
import constants from '../../constants';

describe('TestSessionService', () => {
    const route = `${constants.API_PREFIX_URL}/test_sessions`;
    const mock = new MockAdapter(axios);
    const data = [{
        created_datetime: '2020-10-16T14:28:36.073570',
        end_datetime: '2020-10-16T14:28:35.762000',
        grade: null,
        id: 2,
        max_grade: null,
        name: 'Advanced - Admin User - 2020-10-16T14:28:35.762Z',
        results_cloze: [{
            answers: [{
                answered_correctly: 0,
                attempted: false,
                cloze_question_id: 1,
                end_time: null,
                id: 6,
                results_cloze: 2,
                results_cloze_id: 2,
                seen: true,
                start_time: null,
                text: null,
            },
            ],
            cloze_id: 1,
            end: '2020-10-16T14:28:23.220000',
            id: 2,
            start: '2020-10-16T14:28:17.038000',
            test_session_id: 2,
            text: null,
        }],
        results_rc: [{
            answers: [{
                answered_correctly: 0,
                attempted: true,
                end_time: '2020-10-16T14:28:08.272000',
                id: 11,
                rc_question_id: 11,
                results_rc: 2,
                results_rc_id: 2,
                seen: true,
                start_time: '2020-10-16T14:28:05.950000',
                text: 'Has a double-meaning both as a pun on the topic of plants and a literal meaning of "to replace"',
            },
            ],
            end: '2020-10-16T14:28:15.791000',
            id: 2,
            rc_id: 1,
            start: '2020-10-16T14:28:05.946000',
            test_session_id: 2,
            text: null,
        }],
        results_vocabulary: [{
            answers: [{
                answered_correctly: 0,
                attempted: true,
                end_time: '2020-10-16T14:27:56.694000',
                id: 11,
                results_vocabulary: 2,
                results_vocabulary_id: 2,
                seen: true,
                start_time: '2020-10-16T14:27:54.184000',
                text: 'defeat',
                vocabulary_id: 9,
            },
            ],
            end: '2020-10-16T14:28:04.871000',
            id: 2,
            start: '2020-10-16T14:27:54.180000',
            test_session_id: 2,
            text: null,
        }],
        results_writing: [{
            answer: {
                answered_correctly: null,
                attempted: true,
                end_time: '2020-10-16T14:28:28.614000',
                id: 1,
                results_writing: 1,
                results_writing_id: 1,
                seen: true,
                start_time: '2020-10-16T14:28:24.960000',
                text: 'I am groot',
            },
            end: '2020-10-16T14:28:28.615000',
            id: 1,
            start: '2020-10-16T14:28:24.955000',
            test_session_id: 2,
            text: null,
            writing_id: 1,
        },
        {
            answer: {
                answered_correctly: null,
                attempted: true,
                end_time: '2020-10-16T14:28:34.501000',
                id: 2,
                results_writing: 2,
                results_writing_id: 2,
                seen: true,
                start_time: '2020-10-16T14:28:28.614000',
                text: "It's true",
            },
            end: '2020-10-16T14:28:34.496000',
            id: 2,
            start: '2020-10-16T14:28:28.615000',
            test_session_id: 2,
            text: null,
            writing_id: 2,
        },
        ],
        start_datetime: '2020-10-16T14:27:52.492000',
        test: {
            id: 3,
            immutable: true,
            mandatory_test_user_field_category: [{
                display: 'Student Id',
                id: 1,
                name: 'student_id',
                user_field_type: {
                    enumeration: null,
                    enumeration_id: null,
                    id: 1,
                    name: 'text',
                },
                user_field_type_id: 1,
            }],
            name: 'Advanced',
            order: [],
            test_cloze: [{
                filename: null,
                id: 1,
                immutable: true,
                name: 'Cloze-1',
                questions: [{
                    cloze_id: 1,
                    correct: 3,
                    difficulty: 1,
                    id: 1,
                    options: [],
                    text: 'that',
                    typed: true,
                },
                {
                    cloze_id: 1,
                    correct: 4,
                    difficulty: 1,
                    id: 2,
                    options: [{
                        cloze_question_id: 2,
                        id: 1,
                        text: 'being disappeared',
                    },
                    {
                        cloze_question_id: 2,
                        id: 2,
                        text: 'to be disappeared',
                    },
                    {
                        cloze_question_id: 2,
                        id: 3,
                        text: 'to have disappeared',
                    },
                    {
                        cloze_question_id: 2,
                        id: 4,
                        text: 'to disappear',
                    },
                    {
                        cloze_question_id: 2,
                        id: 5,
                        text: 'having disappeared',
                    },
                    ],
                    text: 'to disappear',
                    typed: false,
                },
                {
                    cloze_id: 1,
                    correct: 1,
                    difficulty: 1,
                    id: 3,
                    options: [{
                        cloze_question_id: 3,
                        id: 6,
                        text: 'until',
                    },
                    {
                        cloze_question_id: 3,
                        id: 7,
                        text: 'since',
                    },
                    {
                        cloze_question_id: 3,
                        id: 8,
                        text: 'after',
                    },
                    {
                        cloze_question_id: 3,
                        id: 9,
                        text: 'by the time',
                    },
                    {
                        cloze_question_id: 3,
                        id: 10,
                        text: 'unless',
                    },
                    ],
                    text: 'until',
                    typed: false,
                },
                {
                    cloze_id: 1,
                    correct: 3,
                    difficulty: 1,
                    id: 4,
                    options: [{
                        cloze_question_id: 4,
                        id: 11,
                        text: 'reluctantly',
                    },
                    {
                        cloze_question_id: 4,
                        id: 12,
                        text: 'accidentally',
                    },
                    {
                        cloze_question_id: 4,
                        id: 13,
                        text: 'slowly',
                    },
                    {
                        cloze_question_id: 4,
                        id: 14,
                        text: 'passionately',
                    },
                    {
                        cloze_question_id: 4,
                        id: 15,
                        text: 'carefully',
                    },
                    ],
                    text: 'slowly',
                    typed: false,
                },
                {
                    cloze_id: 1,
                    correct: 3,
                    difficulty: 1,
                    id: 5,
                    options: [{
                        cloze_question_id: 5,
                        id: 16,
                        text: 'the same',
                    },
                    {
                        cloze_question_id: 5,
                        id: 17,
                        text: 'alike',
                    },
                    {
                        cloze_question_id: 5,
                        id: 18,
                        text: 'just as',
                    },
                    {
                        cloze_question_id: 5,
                        id: 19,
                        text: 'by the way',
                    },
                    {
                        cloze_question_id: 5,
                        id: 20,
                        text: 'similar to',
                    },
                    ],
                    text: 'just as',
                    typed: false,
                },
                ],
                test_category: {
                    id: 3,
                    name: 'Default',
                    test_type: {
                        id: 3,
                        name: 'Cloze',
                    },
                    test_type_id: 3,
                },
                test_category_id: 3,
                text: 'Can we see *that <typed/><as>* the earth is a globe? Yes, we can, when we watch a ship that sails out to sea. If we watch closely, we see that the ship begins *to disappear<being disappeared, to be disappeared, to have disappeared, having disappeared>* . The bottom of the ship disappears first, and then the ship seems to sink lower and lower, *until<since, by the time, after, unless>* we can only see the top of the ship, and then we see nothing at all. What is hiding the ship from us? It is the earth. Stick a pin most of the way into an orange, and *slowly <reluctantly, accidentally, passionately, carefully>* turn the orange away from you. You will see the pin disappear, *just as <the same, alike,  just as, by the way, similar to>* a ship does on the earth.',
                time_limit: 600,
                type: null,
                unremovable: true,
            }],
            test_rc: [{
                filename: '',
                id: 1,
                immutable: true,
                name: 'RC-1',
                questions: [{
                    correct: 1,
                    difficulty: 1,
                    id: 11,
                    options: [{
                        id: 41,
                        rc_question: 11,
                        rc_question_id: 11,
                        text: 'inquisitive',
                    },
                    {
                        id: 42,
                        rc_question: 11,
                        rc_question_id: 11,
                        text: 'Has a double-meaning both as a pun on the topic of plants and a literal meaning of "to replace"',
                    },
                    {
                        id: 43,
                        rc_question: 11,
                        rc_question_id: 11,
                        text: 'Is a synonym for "to plant again"',
                    },
                    {
                        id: 44,
                        rc_question: 11,
                        rc_question_id: 11,
                        text: 'Has the same meaning as "to plant," with extra emphasis',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'The word "supplanted" in paragraph 1',
                },
                {
                    correct: 3,
                    difficulty: 1,
                    id: 12,
                    options: [{
                        id: 45,
                        rc_question: 12,
                        rc_question_id: 12,
                        text: 'That giant sequoias are more resilient than other tree species',
                    },
                    {
                        id: 46,
                        rc_question: 12,
                        rc_question_id: 12,
                        text: 'That old trees are as productive at photosynthesis as younger ones',
                    },
                    {
                        id: 47,
                        rc_question: 12,
                        rc_question_id: 12,
                        text: 'That only giant sequoias may be named after historical figures',
                    },
                    {
                        id: 48,
                        rc_question: 12,
                        rc_question_id: 12,
                        text: 'That large trees grow more slowly as they age',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'One common myth about trees that The President helps disprove is',
                },
                {
                    correct: 2,
                    difficulty: 1,
                    id: 13,
                    options: [{
                        id: 49,
                        rc_question: 13,
                        rc_question_id: 13,
                        text: 'Their natural beauty can have health benefits for those who travel to wildlife preserves to see them',
                    },
                    {
                        id: 50,
                        rc_question: 13,
                        rc_question_id: 13,
                        text: 'They represent centuries of natural history that no other living things do',
                    },
                    {
                        id: 51,
                        rc_question: 13,
                        rc_question_id: 13,
                        text: 'Because of their size, they can process more carbon dioxide than other trees, which can have significant benefits for the atmosphere',
                    },
                    {
                        id: 52,
                        rc_question: 13,
                        rc_question_id: 13,
                        text: 'Their resilient bark may have eventual uses in human medicine.',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'What is the primary benefit that Sillett and other researchers suggest that giant sequoias may have?',
                },
                {
                    correct: 3,
                    difficulty: 1,
                    id: 14,
                    options: [{
                        id: 53,
                        rc_question: 14,
                        rc_question_id: 14,
                        text: 'Even when the sequoias fall, they do not decay and so send less carbon into the air',
                    },
                    {
                        id: 54,
                        rc_question: 14,
                        rc_question_id: 14,
                        text: 'White firs are more plentiful because they grow and decay more quickly than sequoias',
                    },
                    {
                        id: 55,
                        rc_question: 14,
                        rc_question_id: 14,
                        text: 'The giant sequoias are completely resistant to death',
                    },
                    {
                        id: 56,
                        rc_question: 14,
                        rc_question_id: 14,
                        text: 'White firs are essential because when they decompose they emit necessary nutrients',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'The giant sequoias are compared to white firs to demonstrate that?',
                },
                {
                    correct: 2,
                    difficulty: 1,
                    id: 15,
                    options: [{
                        id: 57,
                        rc_question: 15,
                        rc_question_id: 15,
                        text: '1850',
                    },
                    {
                        id: 58,
                        rc_question: 15,
                        rc_question_id: 15,
                        text: '2012',
                    },
                    {
                        id: 59,
                        rc_question: 15,
                        rc_question_id: 15,
                        text: '1580',
                    },
                    {
                        id: 60,
                        rc_question: 15,
                        rc_question_id: 15,
                        text: 'The President has grown every year of its life',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'The President has grown every year EXCEPT',
                },
                {
                    correct: 1,
                    difficulty: 1,
                    id: 16,
                    options: [{
                        id: 61,
                        rc_question: 16,
                        rc_question_id: 16,
                        text: 'They are resistant to diseases that can affect other tree species',
                    },
                    {
                        id: 62,
                        rc_question: 16,
                        rc_question_id: 16,
                        text: 'Their size makes them less vulnerable to animal attacks',
                    },
                    {
                        id: 63,
                        rc_question: 16,
                        rc_question_id: 16,
                        text: 'They are resistant to pests that commonly inhabit trees',
                    },
                    {
                        id: 64,
                        rc_question: 16,
                        rc_question_id: 16,
                        text: 'Their thick bark protects them from wildfires.',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'All of the following contribute to the lifespan of the giant sequoia EXCEPT',
                },
                {
                    correct: 1,
                    difficulty: 1,
                    id: 17,
                    options: [{
                        id: 65,
                        rc_question: 17,
                        rc_question_id: 17,
                        text: 'The size rankings of various large sequoias is being reevaluated',
                    },
                    {
                        id: 66,
                        rc_question: 17,
                        rc_question_id: 17,
                        text: 'Human security will be employed to protect these valuable trees',
                    },
                    {
                        id: 67,
                        rc_question: 17,
                        rc_question_id: 17,
                        text: 'Wildlife parks will bring in new equipment to ensure the safety of the trees',
                    },
                    {
                        id: 68,
                        rc_question: 17,
                        rc_question_id: 17,
                        text: 'A new schedule of shifts will be made for studying the trees',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'The term "changing of the guard" in Paragraph 10 means',
                },
                {
                    correct: 1,
                    difficulty: 1,
                    id: 18,
                    options: [{
                        id: 69,
                        rc_question: 18,
                        rc_question_id: 18,
                        text: 'Current sequoia reserves will be altered to grow in particular patterns',
                    },
                    {
                        id: 70,
                        rc_question: 18,
                        rc_question_id: 18,
                        text: 'That sequoias may be specially grown in the future for the sole purpose of filtering carbon from the air',
                    },
                    {
                        id: 71,
                        rc_question: 18,
                        rc_question_id: 18,
                        text: 'New forests may be grown globally to promote the beauty of the species',
                    },
                    {
                        id: 72,
                        rc_question: 18,
                        rc_question_id: 18,
                        text: 'Wildlife parks will make more of an effort in the future to direct visitors to the sequoia forests',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'What does the term "cultivated sequoia forests" in Paragraph 14 imply?',
                },
                {
                    correct: 1,
                    difficulty: 1,
                    id: 19,
                    options: [{
                        id: 73,
                        rc_question: 19,
                        rc_question_id: 19,
                        text: 'New Zealand',
                    },
                    {
                        id: 74,
                        rc_question: 19,
                        rc_question_id: 19,
                        text: 'France',
                    },
                    {
                        id: 75,
                        rc_question: 19,
                        rc_question_id: 19,
                        text: 'South America',
                    },
                    {
                        id: 76,
                        rc_question: 19,
                        rc_question_id: 19,
                        text: 'Australia',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'Giant sequoias are native to California, but can also be found in',
                },
                {
                    correct: 3,
                    difficulty: 1,
                    id: 20,
                    options: [{
                        id: 77,
                        rc_question: 20,
                        rc_question_id: 20,
                        text: 'Best of a species',
                    },
                    {
                        id: 78,
                        rc_question: 20,
                        rc_question_id: 20,
                        text: 'Most beautiful',
                    },
                    {
                        id: 79,
                        rc_question: 20,
                        rc_question_id: 20,
                        text: 'The winner of a contest',
                    },
                    {
                        id: 80,
                        rc_question: 20,
                        rc_question_id: 20,
                        text: 'Having individual, unique merit',
                    },
                    ],
                    rc: 1,
                    rc_id: 1,
                    text: 'In the final sentence, the word "superlative" is closest in meaning to',
                },
                ],
                test_category: {
                    id: 2,
                    name: 'Default',
                    test_type: {
                        id: 2,
                        name: 'Reading Comprehension',
                    },
                    test_type_id: 2,
                },
                test_category_id: 2,
                text: "Deep in the Sierra Nevada, the famous General Grant giant sequoia tree is suffering its loss of stature in silence. What once was the world's No. 2 biggest tree has been supplanted thanks to the most comprehensive measurements taken of the largest living things on Earth.\n\n\nThe new No. 2 is The President, a 54,000-cubic-foot gargantuan not far from the Grant in Sequoia National Park. After 3,240 years, the giant sequoia still is growing wider at a consistent rate, which may be what most surprised the scientists examining how the sequoias and coastal redwoods will be affected by climate change and whether these trees have a role to play in combating it.\n\n\n\"I consider it to be the greatest tree in all of the mountains of the world,\" said Stephen Sillett, a redwood researcher whose team from Humboldt State University is seeking to mathematically assess the potential of California's iconic trees to absorb planet-warming carbon dioxide.\n\n\nThe researchers are a part of the 10-year Redwoods and Climate Change Initiative funded by the Save the Redwoods League in San Francisco. The measurements of The President, reported in the current National Geographic, dispelled the previous notion that the big trees grow more slowly in old age.\n\n\n\nIt means, the experts say, the amount of carbon dioxide they absorb during photosynthesis continues to increase over their lifetimes.\n\n\nIn addition to painstaking measurements of every branch and twig, the team took 15 half-centimeter-wide core samples of The President to determine its growth rate, which they learned was stunted in the abnormally cold year of 1580 when temperatures in the Sierra hovered near freezing even in the summer and the trees remained dormant.\n\n\nBut that was an anomaly, Sillett said. The President adds about one cubic meter of wood a year during its short six-month growing season, making it one of the fastest-growing trees in the world. Its 2 billion leaves are thought to be the most of any tree on the planet, which would also make it one of the most efficient at transforming carbon dioxide into nourishing sugars during photosynthesis.\n\n\n\"We're not going to save the world with any one strategy, but part of the value of these great trees is this contribution and we're trying to get a handle on the math behind that,\" Sillett said.\n\n\nAfter the equivalent of 32 working days dangling from ropes in The President, Sillett's team is closer to having a mathematical equation to determine its carbon conversion potential, as it has done with some less famous coastal redwoods. The team has analyzed a representative sample that can be used to model the capacity of the state's signature trees.\n\n\nMore immediately, however, the new measurements could lead to a changing of the guard in the land of giant sequoias. The park would have to update signs and brochures - and someone is going to have to correct the Wikipedia entry for \"List of largest giant sequoias,\" which still has The President at No. 3.\n\n\nNow at 93 feet in circumference and with 45,000 cubic feet of trunk volume and another 9,000 cubic feet in its branches, the tree named for President Warren G. Harding is about 15 percent larger than Grant, also known as America's Christmas Tree. Sliced into one-foot by one-foot cubes, The President would cover a football field.\n\n\nGiant sequoias grow so big and for so long because their wood is resistant to the pests and disease that dwarf the lifespan of other trees, and their thick bark makes them impervious to fast-moving fire.\n\n\nIt's that resiliency that makes sequoias and their taller coastal redwood cousin worthy of intensive protections and even candidates for cultivation to pull carbon from an increasingly warming atmosphere, Sillett said. Unlike white firs, which easily die and decay to send decomposing carbon back into the air, rot-resistant redwoods stay solid for hundreds of years after they fall.\n\n\nThough sequoias are native to California, early settlers traveled with seedlings back to the British Isles and New Zealand, where a 15-foot diameter sequoia that is the world's biggest planted tree took root in 1850. Part of Sillett's studies involves modeling the potential growth rate of cultivated sequoia forests to determine over time how much carbon sequestering might increase.\n\n\nAll of that led him to a spot 7,000 feet high in the Sierra and to The President, which he calls \"the ultimate example of a giant sequoia.\" Compared to the other giants whose silhouettes are bedraggled by lightning strikes, The President's crown is large with burly branches that are themselves as large as tree trunks.\n\n\nThe world's biggest tree is still the nearby General Sherman with about 2,000 cubic feet more volume than the President, but to Sillett it's not a contest.\n\n\n\"They're all superlative in their own way,\" Sillett said.\n",
                time_limit: 600,
                type: null,
                unremovable: true,
            }],
            test_student_class: [],
            test_user_field_category: [{
                display: 'Student Id',
                id: 1,
                name: 'student_id',
                user_field_type: {
                    enumeration: null,
                    enumeration_id: null,
                    id: 1,
                    name: 'text',
                },
                user_field_type_id: 1,
            },
            {
                display: 'First Language',
                id: 2,
                name: 'first_language',
                user_field_type: {
                    enumeration: {
                        id: 2,
                        name: 'Language',
                        values: [{
                            enumeration: 2,
                            enumeration_id: 2,
                            id: 5,
                            text: 'English',
                        },
                        {
                            enumeration: 2,
                            enumeration_id: 2,
                            id: 6,
                            text: 'Mandarin',
                        },
                        {
                            enumeration: 2,
                            enumeration_id: 2,
                            id: 7,
                            text: 'Hindi',
                        },
                        {
                            enumeration: 2,
                            enumeration_id: 2,
                            id: 8,
                            text: 'German',
                        },
                        ],
                    },
                    enumeration_id: 2,
                    id: 10,
                    name: 'Language',
                },
                user_field_type_id: 10,
            },
            {
                display: 'Email',
                id: 3,
                name: 'email',
                user_field_type: {
                    enumeration: null,
                    enumeration_id: null,
                    id: 1,
                    name: 'text',
                },
                user_field_type_id: 1,
            },
            {
                display: 'Phone',
                id: 4,
                name: 'phone',
                user_field_type: {
                    enumeration: null,
                    enumeration_id: null,
                    id: 1,
                    name: 'text',
                },
                user_field_type_id: 1,
            },
            {
                display: 'Address',
                id: 5,
                name: 'address',
                user_field_type: {
                    enumeration: null,
                    enumeration_id: null,
                    id: 1,
                    name: 'text',
                },
                user_field_type_id: 1,
            },
            {
                display: 'Education',
                id: 6,
                name: 'education',
                user_field_type: {
                    enumeration: {
                        id: 3,
                        name: 'University',
                        values: [{
                            enumeration: 3,
                            enumeration_id: 3,
                            id: 9,
                            text: 'Carleton University',
                        },
                        {
                            enumeration: 3,
                            enumeration_id: 3,
                            id: 10,
                            text: 'University of Ottawa',
                        },
                        {
                            enumeration: 3,
                            enumeration_id: 3,
                            id: 11,
                            text: 'McGill University',
                        },
                        ],
                    },
                    enumeration_id: 3,
                    id: 11,
                    name: 'University',
                },
                user_field_type_id: 11,
            },
            ],
            test_vocabulary: [{
                correct: 3,
                difficulty: '10',
                id: 9,
                immutable: true,
                options: [{
                    id: 33,
                    text: 'lock',
                    vocabulary: 9,
                    vocabulary_id: 9,
                },
                {
                    id: 34,
                    text: 'defeat',
                    vocabulary: 9,
                    vocabulary_id: 9,
                },
                {
                    id: 35,
                    text: 'trick',
                    vocabulary: 9,
                    vocabulary_id: 9,
                },
                {
                    id: 36,
                    text: 'decide',
                    vocabulary: 9,
                    vocabulary_id: 9,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'dupe',
            },
            {
                correct: 1,
                difficulty: '10',
                id: 4,
                immutable: true,
                options: [{
                    id: 13,
                    text: 'mysterious',
                    vocabulary: 4,
                    vocabulary_id: 4,
                },
                {
                    id: 14,
                    text: 'invisible',
                    vocabulary: 4,
                    vocabulary_id: 4,
                },
                {
                    id: 15,
                    text: 'fixed',
                    vocabulary: 4,
                    vocabulary_id: 4,
                },
                {
                    id: 16,
                    text: 'quiet',
                    vocabulary: 4,
                    vocabulary_id: 4,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'inscrutable',
            },
            {
                correct: 1,
                difficulty: '10',
                id: 10,
                immutable: true,
                options: [{
                    id: 37,
                    text: 'harmless',
                    vocabulary: 10,
                    vocabulary_id: 10,
                },
                {
                    id: 38,
                    text: 'unavailable',
                    vocabulary: 10,
                    vocabulary_id: 10,
                },
                {
                    id: 39,
                    text: 'sudden',
                    vocabulary: 10,
                    vocabulary_id: 10,
                },
                {
                    id: 40,
                    text: 'upbeat',
                    vocabulary: 10,
                    vocabulary_id: 10,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'innocuous',
            },
            {
                correct: 3,
                difficulty: '10',
                id: 8,
                immutable: true,
                options: [{
                    id: 29,
                    text: 'obtainable',
                    vocabulary: 8,
                    vocabulary_id: 8,
                },
                {
                    id: 30,
                    text: 'absent',
                    vocabulary: 8,
                    vocabulary_id: 8,
                },
                {
                    id: 31,
                    text: 'admitted',
                    vocabulary: 8,
                    vocabulary_id: 8,
                },
                {
                    id: 32,
                    text: 'original',
                    vocabulary: 8,
                    vocabulary_id: 8,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'privy',
            },
            {
                correct: 3,
                difficulty: '5',
                id: 1,
                immutable: true,
                options: [{
                    id: 1,
                    text: 'broken',
                    vocabulary: 1,
                    vocabulary_id: 1,
                },
                {
                    id: 2,
                    text: 'fluffy',
                    vocabulary: 1,
                    vocabulary_id: 1,
                },
                {
                    id: 3,
                    text: 'sharp',
                    vocabulary: 1,
                    vocabulary_id: 1,
                },
                {
                    id: 4,
                    text: 'thin',
                    vocabulary: 1,
                    vocabulary_id: 1,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'keen',
            },
            {
                correct: 3,
                difficulty: '10',
                id: 3,
                immutable: true,
                options: [{
                    id: 9,
                    text: 'rumor',
                    vocabulary: 3,
                    vocabulary_id: 3,
                },
                {
                    id: 10,
                    text: 'load',
                    vocabulary: 3,
                    vocabulary_id: 3,
                },
                {
                    id: 11,
                    text: 'tendency',
                    vocabulary: 3,
                    vocabulary_id: 3,
                },
                {
                    id: 12,
                    text: 'damage',
                    vocabulary: 3,
                    vocabulary_id: 3,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'proclivity',
            },
            {
                correct: 1,
                difficulty: '10',
                id: 2,
                immutable: true,
                options: [{
                    id: 5,
                    text: 'logic',
                    vocabulary: 2,
                    vocabulary_id: 2,
                },
                {
                    id: 6,
                    text: 'kindness',
                    vocabulary: 2,
                    vocabulary_id: 2,
                },
                {
                    id: 7,
                    text: 'envy',
                    vocabulary: 2,
                    vocabulary_id: 2,
                },
                {
                    id: 8,
                    text: 'stupidity',
                    vocabulary: 2,
                    vocabulary_id: 2,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'ratiocination',
            },
            {
                correct: 3,
                difficulty: '10',
                id: 5,
                immutable: true,
                options: [{
                    id: 17,
                    text: 'flavour',
                    vocabulary: 5,
                    vocabulary_id: 5,
                },
                {
                    id: 18,
                    text: 'bias',
                    vocabulary: 5,
                    vocabulary_id: 5,
                },
                {
                    id: 19,
                    text: 'ancestor',
                    vocabulary: 5,
                    vocabulary_id: 5,
                },
                {
                    id: 20,
                    text: 'setback',
                    vocabulary: 5,
                    vocabulary_id: 5,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'progenitor',
            },
            {
                correct: 4,
                difficulty: '10',
                id: 6,
                immutable: true,
                options: [{
                    id: 21,
                    text: 'clammy',
                    vocabulary: 6,
                    vocabulary_id: 6,
                },
                {
                    id: 22,
                    text: 'active',
                    vocabulary: 6,
                    vocabulary_id: 6,
                },
                {
                    id: 23,
                    text: 'nauseating',
                    vocabulary: 6,
                    vocabulary_id: 6,
                },
                {
                    id: 24,
                    text: 'scrawny',
                    vocabulary: 6,
                    vocabulary_id: 6,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'emaciated',
            },
            {
                correct: 2,
                difficulty: '10',
                id: 7,
                immutable: true,
                options: [{
                    id: 25,
                    text: 'fight',
                    vocabulary: 7,
                    vocabulary_id: 7,
                },
                {
                    id: 26,
                    text: 'tempt',
                    vocabulary: 7,
                    vocabulary_id: 7,
                },
                {
                    id: 27,
                    text: 'slip',
                    vocabulary: 7,
                    vocabulary_id: 7,
                },
                {
                    id: 28,
                    text: 'relax',
                    vocabulary: 7,
                    vocabulary_id: 7,
                },
                ],
                test_category: {
                    id: 1,
                    name: 'Default',
                    test_type: {
                        id: 1,
                        name: 'Vocabulary',
                    },
                    test_type_id: 1,
                },
                test_category_id: 1,
                time_limit: 20,
                type: 'synonym',
                unremovable: true,
                word: 'entice',
            },
            ],
            test_writing: [{
                filename: '',
                id: 1,
                immutable: true,
                name: 'Weather',
                question: 'Please write a short essay, about 200-300 words on the weather.',
                test_category: {
                    id: 4,
                    name: 'Default',
                    test_type: {
                        id: 4,
                        name: 'Writing',
                    },
                    test_type_id: 4,
                },
                test_category_id: 4,
                time_limit: 900,
                type: 'text',
                unremovable: true,
                word_limit: 300,
            },
            {
                filename: '',
                id: 2,
                immutable: true,
                name: 'Football',
                question: 'Please write a short essay, about 400-500 words on your favourite Football team.',
                test_category: {
                    id: 4,
                    name: 'Default',
                    test_type: {
                        id: 4,
                        name: 'Writing',
                    },
                    test_type_id: 4,
                },
                test_category_id: 4,
                time_limit: 900,
                type: 'text',
                unremovable: true,
                word_limit: 500,
            },
            ],
            unremovable: true,
        },
        test_id: 3,
        user: {
            first_name: 'Admin',
            id: 5,
            last_name: 'User',
            name: 'admin',
        },
        user_id: '5',
    },
    {
        created_datetime: '2020-10-15T20:27:28.469712',
        end_datetime: '2020-10-15T20:27:28.255000',
        grade: null,
        id: 1,
        max_grade: null,
        name: 'Beginner - Admin User - 2020-10-15T20:27:28.255Z',
        result_as_json: null,
        results_cloze: [{
            answers: [{
                answered_correctly: 0,
                attempted: false,
                cloze_question_id: 1,
                end_time: null,
                id: 1,
                results_cloze: 1,
                results_cloze_id: 1,
                seen: true,
                start_time: null,
                text: null,
            },
            ],
            cloze_id: 1,
            end: '2020-10-15T20:27:25.747000',
            id: 1,
            start: '2020-10-15T20:27:23.884000',
            test_session_id: 1,
            text: null,
        }],
        results_rc: [{
            answers: [{
                answered_correctly: 0,
                attempted: false,
                end_time: null,
                id: 1,
                rc_question_id: 11,
                results_rc: 1,
                results_rc_id: 1,
                seen: true,
                start_time: '2020-10-15T20:27:20.301000',
                text: null,
            },
            ],
            end: '2020-10-15T20:27:22.887000',
            id: 1,
            rc_id: 1,
            start: '2020-10-15T20:27:20.296000',
            test_session_id: 1,
            text: null,
        }],
        results_vocabulary: [{
            answers: [{
                answered_correctly: 0,
                attempted: false,
                end_time: '2020-10-15T20:27:17.595000',
                id: 1,
                results_vocabulary: 1,
                results_vocabulary_id: 1,
                seen: true,
                start_time: '2020-10-15T20:27:16.772000',
                text: null,
                vocabulary_id: 26,
            },
            ],
            end: '2020-10-15T20:27:18.846000',
            id: 1,
            start: '2020-10-15T20:27:16.768000',
            test_session_id: 1,
            text: null,
        }],
    },
    ];
    beforeAll(() => {
        mock.onGet(route).reply(200, data);
        mock.onGet(`${route}?id=1`).reply(200, data[0]);
        mock.onPost(route).reply(config => [200, config.data]);
        mock.onPut(route).reply(config => [200, config.data]);
        mock.onGet(`${route}/count`).reply(200, { count: data.length });
        mock.onGet(`${route}/export`).reply(config => [200, {
            responseType: config.responseType,
            headers: config.headers,
        }]);
        mock.onGet(`${route}/export?id=1`).reply(config => [200, {
            responseType: config.responseType,
            headers: config.headers,
        }]);
    });

    test('prefix', () => expect(service.getUrl()).toBe(route));

    test('get', async () => {
        const response = await service.get();
        expect(response).toEqual(expect.objectContaining(data));
    });

    test('get an item', async () => {
        const response = await service.get({ id: 1 });
        expect(response).toEqual(expect.objectContaining(data[0]));
    });

    test('add', async () => {
        const request = data[0];
        const response = await service.add(request);
        expect(response).toEqual(expect.objectContaining(data[0]));
    });

    test('update', async () => {
        const request = data[0];
        const response = await service.update(request);
        expect(response).toEqual(expect.objectContaining(data[0]));
    });

    test('count', async () => {
        const response = await service.count();
        expect(response).toEqual(expect.objectContaining({ count: data.length }));
    });

    test('export', async () => {
        const response = await service.export();
        expect(response.responseType).toEqual('arraybuffer');
        expect(response.headers).toEqual(expect.objectContaining({ 'Content-Type': 'blob' }));
    });

    test('export an item', async () => {
        const response = await service.export(1);
        expect(response.responseType).toEqual('arraybuffer');
        expect(response.headers).toEqual(expect.objectContaining({ 'Content-Type': 'blob' }));
    });
});
