import { configureStore } from '@reduxjs/toolkit';
import { reducers } from '../slices';

export default configureStore({
    reducer: reducers,
    preloadedState: {
        userSession: {
            id: 5,
            name: 'admin',
            firstName: 'Admin',
            lastName: 'User',
            displayName: 'Admin User',
            roles: [
                {
                    authorizations: [
                        {
                            category: 'Routes',
                            dependencies: [],
                            id: 1,
                            name: 'admin',
                            text: 'Grants admin routes access',
                        },
                        {
                            category: 'Routes',
                            dependencies: [],
                            id: 2,
                            name: 'test',
                            text: 'Grants test routes access',
                        },
                        {
                            category: 'User',
                            dependencies: [
                                'read-role',
                                'read-user-field-type',
                            ],
                            id: 3,
                            name: 'read-user',
                            text: 'Grants access to read user(s)',
                        },
                        {
                            category: 'User',
                            dependencies: [
                                'read-user',
                                'read-role',
                                'read-user-field-type',
                            ],
                            id: 4,
                            name: 'create-user',
                            text: 'Grants access to create user(s)',
                        },
                        {
                            category: 'User',
                            dependencies: [
                                'read-user',
                                'read-role',
                                'read-user-field-type',
                            ],
                            id: 5,
                            name: 'update-user',
                            text: 'Grants access to update user(s)',
                        },
                        {
                            category: 'User',
                            dependencies: [
                                'read-user',
                                'read-role',
                                'read-user-field-type',
                            ],
                            id: 6,
                            name: 'delete-user',
                            text: 'Grants access to delete user(s)',
                        },
                        {
                            category: 'User',
                            dependencies: [
                                'read-user',
                                'read-role',
                                'read-user-field-type',
                            ],
                            id: 7,
                            name: 'export-user',
                            text: 'Grants access to export user(s)',
                        },
                        {
                            category: 'User',
                            dependencies: [
                                'read-user',
                            ],
                            id: 8,
                            name: 'import-user',
                            text: 'Grants access to import user(s)',
                        },
                        {
                            category: 'Student Class',
                            dependencies: [
                                'read-user',
                            ],
                            id: 9,
                            name: 'read-student-class',
                            text: 'Grants access to read student class(es)',
                        },
                        {
                            category: 'Student Class',
                            dependencies: [
                                'read-student-class',
                                'read-user',
                            ],
                            id: 10,
                            name: 'create-student-class',
                            text: 'Grants access to create student class(es)',
                        },
                        {
                            category: 'Student Class',
                            dependencies: [
                                'read-student-class',
                                'read-user',
                            ],
                            id: 11,
                            name: 'update-student-class',
                            text: 'Grants access to update student class(es)',
                        },
                        {
                            category: 'Student Class',
                            dependencies: [
                                'read-student-class',
                                'read-user',
                            ],
                            id: 12,
                            name: 'delete-student-class',
                            text: 'Grants access to delete student class(es)',
                        },
                        {
                            category: 'Student Class',
                            dependencies: [
                                'read-student-class',
                                'read-user',
                            ],
                            id: 13,
                            name: 'export-student-class',
                            text: 'Grants access to export student class(es)',
                        },
                        {
                            category: 'Student Class',
                            dependencies: [
                                'read-student-class',
                            ],
                            id: 14,
                            name: 'import-student-class',
                            text: 'Grants access to import student class(es)',
                        },
                        {
                            category: 'Test',
                            dependencies: [
                                'read-student-class',
                                'read-demographic-questionnaire-field',
                                'read-vocabulary',
                                'read-reading-comprehension',
                                'read-cloze',
                                'read-writing',
                            ],
                            id: 15,
                            name: 'read-test',
                            text: 'Grants access to read test(s)',
                        },
                        {
                            category: 'Test',
                            dependencies: [
                                'read-test',
                                'read-student-class',
                                'read-demographic-questionnaire-field',
                                'read-vocabulary',
                                'read-reading-comprehension',
                                'read-cloze',
                                'read-writing',
                            ],
                            id: 16,
                            name: 'create-test',
                            text: 'Grants access to create test(s)',
                        },
                        {
                            category: 'Test',
                            dependencies: [
                                'read-test',
                                'read-student-class',
                                'read-demographic-questionnaire-field',
                                'read-vocabulary',
                                'read-reading-comprehension',
                                'read-cloze',
                                'read-writing',
                            ],
                            id: 17,
                            name: 'update-test',
                            text: 'Grants access to update test(s)',
                        },
                        {
                            category: 'Test',
                            dependencies: [
                                'read-test',
                                'read-student-class',
                                'read-demographic-questionnaire-field',
                                'read-vocabulary',
                                'read-reading-comprehension',
                                'read-cloze',
                                'read-writing',
                            ],
                            id: 18,
                            name: 'delete-test',
                            text: 'Grants access to delete test(s)',
                        },
                        {
                            category: 'Test',
                            dependencies: [
                                'read-test',
                                'read-student-class',
                                'read-demographic-questionnaire-field',
                                'read-vocabulary',
                                'read-reading-comprehension',
                                'read-cloze',
                                'read-writing',
                            ],
                            id: 19,
                            name: 'export-test',
                            text: 'Grants access to delete test(s)',
                        },
                        {
                            category: 'Past Result',
                            dependencies: [],
                            id: 20,
                            name: 'read-test-session',
                            text: 'Grants access to read test-session(s)',
                        },
                        {
                            category: 'Past Result',
                            dependencies: [
                                'read-test-session',
                            ],
                            id: 21,
                            name: 'export-test-session',
                            text: 'Grants access to export test-session(s)',
                        },
                        {
                            category: 'Past Result',
                            dependencies: [
                                'read-test-session',
                            ],
                            id: 22,
                            name: 'create-test-session',
                            text: 'Grants access to create test-session(s)',
                        },
                        {
                            category: 'Past Result',
                            dependencies: [
                                'read-test-session',
                            ],
                            id: 23,
                            name: 'delete-test-session',
                            text: 'Grants access to delete test-session(s)',
                        },
                        {
                            category: 'Past Result',
                            dependencies: [
                                'read-test-session',
                            ],
                            id: 24,
                            name: 'update-test-session',
                            text: 'Grants access to update test-session(s)',
                        },
                        {
                            category: 'Test Type',
                            dependencies: [],
                            id: 25,
                            name: 'read-test-type',
                            text: 'Grants access to read test-type(s)',
                        },
                        {
                            category: 'Test Type',
                            dependencies: [
                                'read-test-type',
                            ],
                            id: 26,
                            name: 'create-test-type',
                            text: 'Grants access to create test-type(s)',
                        },
                        {
                            category: 'Test Type',
                            dependencies: [
                                'read-test-type',
                            ],
                            id: 27,
                            name: 'delete-test-type',
                            text: 'Grants access to delete test-type(s)',
                        },
                        {
                            category: 'Test Type',
                            dependencies: [
                                'read-test-type',
                            ],
                            id: 28,
                            name: 'update-test-type',
                            text: 'Grants access to update test-type(s)',
                        },
                        {
                            category: 'Vocabulary',
                            dependencies: [
                                'read-test-category',
                            ],
                            id: 29,
                            name: 'read-vocabulary',
                            text: 'Grants access to read vocabulary(ies)',
                        },
                        {
                            category: 'Vocabulary',
                            dependencies: [
                                'read-vocabulary',
                                'read-test-category',
                            ],
                            id: 30,
                            name: 'create-vocabulary',
                            text: 'Grants access to create vocabulary(ies)',
                        },
                        {
                            category: 'Vocabulary',
                            dependencies: [
                                'read-vocabulary',
                                'read-test-category',
                            ],
                            id: 31,
                            name: 'update-vocabulary',
                            text: 'Grants access to update vocabulary(ies)',
                        },
                        {
                            category: 'Vocabulary',
                            dependencies: [
                                'read-vocabulary',
                                'read-test-category',
                            ],
                            id: 32,
                            name: 'delete-vocabulary',
                            text: 'Grants access to delete vocabulary(ies)',
                        },
                        {
                            category: 'Vocabulary',
                            dependencies: [
                                'read-vocabulary',
                                'read-test-category',
                            ],
                            id: 33,
                            name: 'export-vocabulary',
                            text: 'Grants access to export vocabulary(ies)',
                        },
                        {
                            category: 'Vocabulary',
                            dependencies: [
                                'read-vocabulary',
                            ],
                            id: 34,
                            name: 'import-vocabulary',
                            text: 'Grants access to import vocabulary(ies)',
                        },
                        {
                            category: 'Reading',
                            dependencies: [
                                'read-test-category',
                            ],
                            id: 35,
                            name: 'read-reading-comprehension',
                            text: 'Grants access to read reading(s)',
                        },
                        {
                            category: 'Reading',
                            dependencies: [
                                'read-reading-comprehension',
                                'read-test-category',
                            ],
                            id: 36,
                            name: 'create-reading-comprehension',
                            text: 'Grants access to create reading(s)',
                        },
                        {
                            category: 'Reading',
                            dependencies: [
                                'read-reading-comprehension',
                                'read-test-category',
                            ],
                            id: 37,
                            name: 'update-reading-comprehension',
                            text: 'Grants access to update reading(s)',
                        },
                        {
                            category: 'Reading',
                            dependencies: [
                                'read-reading-comprehension',
                                'read-test-category',
                            ],
                            id: 38,
                            name: 'delete-reading-comprehension',
                            text: 'Grants access to delete reading(s)',
                        },
                        {
                            category: 'Reading',
                            dependencies: [
                                'read-reading-comprehension',
                                'read-test-category',
                            ],
                            id: 39,
                            name: 'export-reading-comprehension',
                            text: 'Grants access to export reading(s)',
                        },
                        {
                            category: 'Reading',
                            dependencies: [
                                'read-reading-comprehension',
                                'read-test-category',
                            ],
                            id: 40,
                            name: 'import-reading-comprehension',
                            text: 'Grants access to import reading(s)',
                        },
                        {
                            category: 'Cloze',
                            dependencies: [
                                'read-test-category',
                            ],
                            id: 41,
                            name: 'read-cloze',
                            text: 'Grants access to read cloze(s)',
                        },
                        {
                            category: 'Cloze',
                            dependencies: [
                                'read-cloze',
                                'read-test-category',
                            ],
                            id: 42,
                            name: 'create-cloze',
                            text: 'Grants access to create cloze(s)',
                        },
                        {
                            category: 'Cloze',
                            dependencies: [
                                'read-cloze',
                                'read-test-category',
                            ],
                            id: 43,
                            name: 'update-cloze',
                            text: 'Grants access to update cloze(s)',
                        },
                        {
                            category: 'Cloze',
                            dependencies: [
                                'read-cloze',
                                'read-test-category',
                            ],
                            id: 44,
                            name: 'delete-cloze',
                            text: 'Grants access to delete cloze(s)',
                        },
                        {
                            category: 'Cloze',
                            dependencies: [
                                'read-cloze',
                                'read-test-category',
                            ],
                            id: 45,
                            name: 'export-cloze',
                            text: 'Grants access to export cloze(s)',
                        },
                        {
                            category: 'Cloze',
                            dependencies: [
                                'read-cloze',
                            ],
                            id: 46,
                            name: 'import-cloze',
                            text: 'Grants access to export cloze(s)',
                        },
                        {
                            category: 'Writing',
                            dependencies: [
                                'read-test-category',
                            ],
                            id: 47,
                            name: 'read-writing',
                            text: 'Grants access to read writing(s)',
                        },
                        {
                            category: 'Writing',
                            dependencies: [
                                'read-writing',
                                'read-test-category',
                            ],
                            id: 48,
                            name: 'create-writing',
                            text: 'Grants access to create writing(s)',
                        },
                        {
                            category: 'Writing',
                            dependencies: [
                                'read-writing',
                                'read-test-category',
                            ],
                            id: 49,
                            name: 'update-writing',
                            text: 'Grants access to update writing(s)',
                        },
                        {
                            category: 'Writing',
                            dependencies: [
                                'read-writing',
                                'read-test-category',
                            ],
                            id: 50,
                            name: 'delete-writing',
                            text: 'Grants access to delete writing(s)',
                        },
                        {
                            category: 'Writing',
                            dependencies: [
                                'read-writing',
                                'read-test-category',
                            ],
                            id: 51,
                            name: 'export-writing',
                            text: 'Grants access to export writing(s)',
                        },
                        {
                            category: 'Writing',
                            dependencies: [
                                'read-writing',
                                'read-test-category',
                            ],
                            id: 52,
                            name: 'import-writing',
                            text: 'Grants access to import writing(s)',
                        },
                        {
                            category: 'Test Category',
                            dependencies: [
                                'read-test-type',
                            ],
                            id: 53,
                            name: 'read-test-category',
                            text: 'Grants access to read test category(ies)',
                        },
                        {
                            category: 'Test Category',
                            dependencies: [
                                'read-test-category',
                                'read-test-type',
                            ],
                            id: 54,
                            name: 'create-test-category',
                            text: 'Grants access to create test category(ies)',
                        },
                        {
                            category: 'Test Category',
                            dependencies: [
                                'read-test-category',
                                'read-test-type',
                            ],
                            id: 55,
                            name: 'update-test-category',
                            text: 'Grants access to update test category(ies)',
                        },
                        {
                            category: 'Test Category',
                            dependencies: [
                                'read-test-category',
                                'read-test-type',
                            ],
                            id: 56,
                            name: 'delete-test-category',
                            text: 'Grants access to delete test category(ies)',
                        },
                        {
                            category: 'Test Category',
                            dependencies: [
                                'read-test-category',
                                'read-test-type',
                            ],
                            id: 57,
                            name: 'export-test-category',
                            text: 'Grants access to export test category(ies)',
                        },
                        {
                            category: 'Demographic Questionnaire Field',
                            dependencies: [
                                'read-user-field-type',
                            ],
                            id: 58,
                            name: 'read-demographic-questionnaire-field',
                            text: 'Grants access to read demographic questionnaire field(s)',
                        },
                        {
                            category: 'Demographic Questionnaire Field',
                            dependencies: [
                                'read-demographic-questionnaire-field',
                                'read-user-field-type',
                            ],
                            id: 59,
                            name: 'create-demographic-questionnaire-field',
                            text: 'Grants access to create demographic questionnaire field(s)',
                        },
                        {
                            category: 'Demographic Questionnaire Field',
                            dependencies: [
                                'read-demographic-questionnaire-field',
                                'read-user-field-type',
                            ],
                            id: 60,
                            name: 'update-demographic-questionnaire-field',
                            text: 'Grants access to update demographic questionnaire field(s)',
                        },
                        {
                            category: 'Demographic Questionnaire Field',
                            dependencies: [
                                'read-demographic-questionnaire-field',
                                'read-user-field-type',
                            ],
                            id: 61,
                            name: 'delete-demographic-questionnaire-field',
                            text: 'Grants access to delete demographic questionnaire field(s)',
                        },
                        {
                            category: 'Demographic Questionnaire Field',
                            dependencies: [
                                'read-demographic-questionnaire-field',
                                'read-user-field-type',
                            ],
                            id: 62,
                            name: 'export-demographic-questionnaire-field',
                            text: 'Grants access to export demographic questionnaire field(s)',
                        },
                        {
                            category: 'User Field Type',
                            dependencies: [
                                'read-enumeration',
                            ],
                            id: 63,
                            name: 'read-user-field-type',
                            text: 'Grants access to read user field type(s)',
                        },
                        {
                            category: 'User Field Type',
                            dependencies: [
                                'read-user-field-type',
                                'read-enumeration',
                            ],
                            id: 64,
                            name: 'create-user-field-type',
                            text: 'Grants access to create user field type(s)',
                        },
                        {
                            category: 'User Field Type',
                            dependencies: [
                                'read-user-field-type',
                                'read-enumeration',
                            ],
                            id: 65,
                            name: 'update-user-field-type',
                            text: 'Grants access to update user field type(s)',
                        },
                        {
                            category: 'User Field Type',
                            dependencies: [
                                'read-user-field-type',
                                'read-enumeration',
                            ],
                            id: 66,
                            name: 'delete-user-field-type',
                            text: 'Grants access to delete user field type(s)',
                        },
                        {
                            category: 'Enumeration',
                            dependencies: [],
                            id: 67,
                            name: 'read-enumeration',
                            text: 'Grants access to read user enumeration(s)',
                        },
                        {
                            category: 'Enumeration',
                            dependencies: [
                                'read-enumeration',
                            ],
                            id: 68,
                            name: 'create-enumeration',
                            text: 'Grants access to create user enumeration(s)',
                        },
                        {
                            category: 'Enumeration',
                            dependencies: [
                                'read-enumeration',
                            ],
                            id: 69,
                            name: 'update-enumeration',
                            text: 'Grants access to update user enumeration(s)',
                        },
                        {
                            category: 'Enumeration',
                            dependencies: [
                                'read-enumeration',
                            ],
                            id: 70,
                            name: 'delete-enumeration',
                            text: 'Grants access to delete user enumeration(s)',
                        },
                        {
                            category: 'Enumeration',
                            dependencies: [
                                'read-enumeration',
                            ],
                            id: 71,
                            name: 'export-enumeration',
                            text: 'Grants access to export user enumeration(s)',
                        },
                        {
                            category: 'Enumeration',
                            dependencies: [
                                'read-enumeration',
                            ],
                            id: 72,
                            name: 'import-enumeration',
                            text: 'Grants access to import user enumeration(s)',
                        },
                        {
                            category: 'Roles',
                            dependencies: [
                                'read-authorization',
                            ],
                            id: 73,
                            name: 'read-role',
                            text: 'Grants access to read role(s)',
                        },
                        {
                            category: 'Roles',
                            dependencies: [
                                'read-role',
                                'read-authorization',
                            ],
                            id: 74,
                            name: 'create-role',
                            text: 'Grants access to create role(s)',
                        },
                        {
                            category: 'Roles',
                            dependencies: [
                                'read-role',
                                'read-authorization',
                            ],
                            id: 75,
                            name: 'update-role',
                            text: 'Grants access to update role(s)',
                        },
                        {
                            category: 'Roles',
                            dependencies: [
                                'read-role',
                                'read-authorization',
                            ],
                            id: 76,
                            name: 'delete-role',
                            text: 'Grants access to delete role(s)',
                        },
                        {
                            category: 'Authorization',
                            dependencies: [],
                            id: 77,
                            name: 'read-authorization',
                            text: 'Grants access to read authorization(s)',
                        },
                    ],
                    id: 1,
                    immutable: true,
                    name: 'Administrator',
                },
            ],
            fields: [
                {
                    id: 15,
                    name: 'student_id',
                    type: 'text',
                    user: 5,
                    userId: 5,
                    value: '1009512312',
                },
                {
                    id: 16,
                    name: 'first_language',
                    type: 'Language',
                    user: 5,
                    userId: 5,
                    value: null,
                },
                {
                    id: 17,
                    name: 'email',
                    type: 'text',
                    user: 5,
                    userId: 5,
                    value: '',
                },
                {
                    id: 18,
                    name: 'phone',
                    type: 'text',
                    user: 5,
                    userId: 5,
                    value: '',
                },
                {
                    id: 19,
                    name: 'address',
                    type: 'text',
                    user: 5,
                    userId: 5,
                    value: '',
                },
                {
                    id: 20,
                    name: 'education',
                    type: 'University',
                    user: 5,
                    userId: 5,
                    value: null,
                },
            ],
            authenticated: true,
        },
        results: {
            loading: false,
            error: false,
            createdDatetime: null,
            endDatetime: null,
            grade: null,
            id: null,
            maxGrade: null,
            name: null,
            startDatetime: null,
        },
        testWizardSession: {
            name: null,
            id: null,
            wizardSteps: [],
            startDatetime: null,
            endDatetime: null,
            createDatetime: null,
            loading: false,
            error: false,
            activeStep: 0,
        },
        readingComprehensionTest: {
            questions: [],
            answers: [],
            correctAnswers: [],
            progressIndex: 0,
            progress: 'not-started',
            loading: false,
            error: false,
            startDatetime: null,
            endDatetime: null,
            startDateTimes: [],
            endDateTimes: [],
            timer: null,
            result: {},
        },
        vocabularyTest: {
            questions: [],
            answers: [],
            correctAnswers: [],
            progressIndex: 0,
            progress: 'not-started',
            loading: false,
            error: false,
            startDatetime: null,
            endDatetime: null,
            timer: null,
            result: {},
        },
        clozeTest: {
            questions: [],
            answers: [],
            correctAnswers: [],
            progressIndex: 0,
            progress: 'not-started',
            loading: false,
            error: false,
            startDatetime: null,
            endDatetime: null,
            startDateTimes: [],
            endDateTimes: [],
            timer: null,
            result: {},
        },
        writingTest: {
            questions: [],
            answers: [],
            progressIndex: 0,
            progress: 'not-started',
            loading: false,
            error: false,
            startDatetime: null,
            endDatetime: null,
            startDateTimes: [],
            endDateTimes: [],
            timer: null,
            result: {},
        },
        timer: {
            tick: 0,
            totalTick: 0,
            timestamp: null,
            timerActive: false,
        },
        dialog: {
            open: false,
            title: 'You have left some questions unanswered',
            confirmed: false,
            canceled: false,
            key: null,
            loading: false,
            text: 'You will not be able to revisit. Are you sure you want to proceed?',
        },
        drawer: {
            enabled: true,
            open: false,
        },
        clone: { data: {} },
    },
});
